# Generated by Django 6.0.5 on 2026-05-16 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_sku_quotation_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='mj',
            field=models.CharField(blank=True, default='ks', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='mj',
            field=models.CharField(blank=True, default='ks', max_length=20, verbose_name='Merná jednotka'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item'),
        ),
    ]
