# Generated by Django 6.0.5 on 2026-05-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_invoiceitem_description_invoiceitem_mj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='partner_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='partner_dic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='partner_ico',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='partner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='partner_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quotation',
            name='partner_dic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='partner_ico',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='partner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Sadzba DPH %'),
        ),
    ]
