# Generated by Django 6.0.5 on 2026-05-17 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_deliverynote_deliverynoteitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rented_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mj', models.CharField(blank=True, default='ks', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='type',
            field=models.CharField(choices=[('standard', 'Klasický výdaj'), ('rental_out', 'Výdaj do prenájmu'), ('rental_return', 'Vratka z prenájmu')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('partner_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('open', 'Otvorená'), ('done', 'Dokončená'), ('invoiced', 'Fakturovaná')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='inventory.partner')),
            ],
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='inventory.project'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='inventory.project'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='inventory.project'),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='rental_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_items', to='inventory.rentalitem'),
        ),
        migrations.CreateModel(
            name='RentalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_out', models.DateField()),
                ('date_in', models.DateField(blank=True, null=True)),
                ('delivery_note_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_in_movements', to='inventory.deliverynote')),
                ('delivery_note_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_out_movements', to='inventory.deliverynote')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_movements', to='inventory.project')),
                ('rental_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.rentalitem')),
            ],
        ),
    ]
