# Generated by Django 6.0.5 on 2026-05-17 11:13 (modified to handle unique constraint)

import django.db.models.deletion
from django.db import migrations, models


def assign_project_numbers(apps, schema_editor):
    Project = apps.get_model('inventory', 'Project')
    from django.utils import timezone
    year = timezone.now().year
    for i, project in enumerate(Project.objects.order_by('id'), start=1):
        project.project_number = f"Z/{i:04d}/{year}"
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rentalitem_deliverynote_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avg_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        # Step 1: Add project_number WITHOUT unique constraint, allowing empty string
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.CharField(blank=True, max_length=30, default=''),
            preserve_default=False,
        ),
        # Step 2: Assign unique project numbers to existing rows
        migrations.RunPython(assign_project_numbers, migrations.RunPython.noop),
        # Step 3: Now add the unique constraint
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='vrf_class',
            field=models.CharField(blank=True, max_length=50, verbose_name='Reflexná trieda VRF'),
        ),
        migrations.AddField(
            model_name='rentalmovement',
            name='contract_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mj', models.CharField(default='ks', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Čaká'), ('ordered', 'Objednané'), ('received', 'Prijaté')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_refs', to='inventory.item')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='inventory.project')),
            ],
        ),
        migrations.CreateModel(
            name='OrderNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('total_qty_needed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qty_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mj', models.CharField(default='ks', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Čaká na objednanie'), ('ordered', 'Objednané'), ('partial', 'Čiastočne prijaté'), ('done', 'Prijaté')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_needs', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderNeedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bom_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.bomitem')),
                ('order_need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_shares', to='inventory.orderneed')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_need_shares', to='inventory.project')),
            ],
        ),
        migrations.CreateModel(
            name='StockDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=100)),
                ('delivery_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_deliveries', to='inventory.partner')),
            ],
        ),
        migrations.CreateModel(
            name='StockDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mj', models.CharField(default='ks', max_length=20)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockdelivery')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_receipts', to='inventory.item')),
                ('order_need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_items', to='inventory.orderneed')),
            ],
        ),
    ]
