# Generated by Django 6.0.5 on 2026-05-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_item_avg_purchase_price_project_project_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='customer_order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Číslo objednávky zákazníka'),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='is_complete_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='minus_clamps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='minus_pole',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='minus_stand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rozmery (napr. 600x600)'),
        ),
        migrations.AddField(
            model_name='item',
            name='retroreflex_class',
            field=models.CharField(blank=True, choices=[('VRF1', 'VRF1'), ('VRF2', 'VRF2'), ('VRF7', 'VRF7 – s koľajnicou')], max_length=10, verbose_name='Trieda retroreflexie'),
        ),
        migrations.AddField(
            model_name='item',
            name='sign_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kód TP117 (napr. 506)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sign_name_sk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slovenský názov/skratka'),
        ),
        migrations.AddField(
            model_name='orderneed',
            name='order_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Číslo objednávky zákazníka'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='is_component',
            field=models.BooleanField(default=False, verbose_name='Je komponent zostáv (stĺpik/svorka/podstavec)'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='retroreflex_class',
            field=models.CharField(blank=True, choices=[('VRF1', 'VRF1'), ('VRF2', 'VRF2'), ('VRF7', 'VRF7 – s koľajnicou')], max_length=10, verbose_name='Trieda retroreflexie'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='sign_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kód TP117 (napr. 506)'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='sign_name_sk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Slovenský názov/skratka'),
        ),
        migrations.AddField(
            model_name='rentalmovement',
            name='is_complete_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalmovement',
            name='minus_clamps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalmovement',
            name='minus_pole',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalmovement',
            name='minus_stand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockdeliveryitem',
            name='rental_item_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_receipts_rental', to='inventory.rentalitem', verbose_name='Cieľová položka Požičovne'),
        ),
        migrations.AddField(
            model_name='stockdeliveryitem',
            name='target_stock',
            field=models.CharField(choices=[('sale', 'Predaj – klasický Sklad'), ('rental', 'Požičovňa – Majetok')], default='sale', max_length=10),
        ),
    ]
