# Generated by Django 6.0.5 on 2026-05-17 14:38

from django.db import migrations


def create_components(apps, schema_editor):
    RentalItem = apps.get_model('inventory', 'RentalItem')
    components = [
        {'sku': 'COMP-PODSTAVEC-V', 'name': 'Podstavec veľký 28kg', 'total_qty': 0, 'rented_qty': 0, 'daily_rate': 0, 'mj': 'ks', 'is_component': True},
        {'sku': 'COMP-PODSTAVEC-M', 'name': 'Podstavec malý', 'total_qty': 0, 'rented_qty': 0, 'daily_rate': 0, 'mj': 'ks', 'is_component': True},
        {'sku': 'COMP-STLPIK-2M', 'name': 'Stĺpik / Jokel 2m', 'total_qty': 0, 'rented_qty': 0, 'daily_rate': 0, 'mj': 'ks', 'is_component': True},
        {'sku': 'COMP-SVORKA', 'name': 'Upínacia svorka', 'total_qty': 0, 'rented_qty': 0, 'daily_rate': 0, 'mj': 'ks', 'is_component': True},
    ]
    for c in components:
        if not RentalItem.objects.filter(sku=c['sku']).exists():
            RentalItem.objects.create(**c)

def reverse_components(apps, schema_editor):
    RentalItem = apps.get_model('inventory', 'RentalItem')
    RentalItem.objects.filter(sku__in=['COMP-PODSTAVEC-V','COMP-PODSTAVEC-M','COMP-STLPIK-2M','COMP-SVORKA']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_tp117_fields_minus_system_renaming'),
    ]

    operations = [
        migrations.RunPython(create_components, reverse_components),
    ]
