# Generated by Django 6.0.5 on 2026-05-17 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_create_rental_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Odoslaná – čaká na príjem'), ('partial', 'Čiastočne prijaté'), ('done', 'Prijaté')], default='sent', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_orders', to='inventory.project')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_orders', to='inventory.partner')),
            ],
        ),
        migrations.CreateModel(
            name='SentOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sent_order_attachments/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.sentorder')),
            ],
        ),
        migrations.CreateModel(
            name='SentOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('qty_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mj', models.CharField(blank=True, default='ks', max_length=20)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_order_refs', to='inventory.item')),
                ('rental_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_order_refs', to='inventory.rentalitem')),
                ('sent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sentorder')),
            ],
        ),
    ]
