# Generated by Django 6.0.5 on 2026-05-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_sent_order_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentorder',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sentorderitem',
            name='vat_rate',
            field=models.IntegerField(default=20),
        ),
    ]
