# Generated by Django 4.2.21 on 2026-05-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_sentorder_prices_expected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recommended_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Doporučená cena dodávateľa'),
        ),
    ]
